openapi: 3.0.3
info:
  title: Spring Boot API Demo
  version: 1.0.0
paths:
  /api/v1:
    get:
      tags:
        - workshop
      operationId: getWorkshopHealth
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkshopHealth'
  /api/v1/saludos:
    get:
      tags:
        - workshop
      operationId: saludarPorGet
      parameters:
        - name: nombre
          in: query
          required: false
          schema:
            type: string
            default: "Mundo"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaludoResponse'
    post:
      tags:
        - workshop
      operationId: saludarPorPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaludoRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaludoResponse'
  /api/v1/simulaciones/prestamo:
    post:
      tags:
        - simulaciones
      operationId: simularPrestamo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrestamoRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrestamoResponse'

components:
  schemas:
    WorkshopHealth:
      type: object
    SaludoRequest:
      type: object
    SaludoResponse:
      type: object
    PrestamoRequest:
      type: object
    PrestamoResponse:
      type: object